FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build
RUN apt-get update && apt-get install -y bash curl
WORKDIR /src

COPY *.sln .
COPY SocialCook/*.csproj ./SocialCook/

RUN dotnet restore

COPY . .

WORKDIR /src/SocialCook
RUN dotnet publish -c Release -o /app/publish

FROM mcr.microsoft.com/dotnet/aspnet:8.0
WORKDIR /app

COPY --from=build /app/publish .



EXPOSE 8081

ENTRYPOINT ["dotnet", "watch", "run",  "SocialCook.dll"]